name: Auto Commit - Keep GitHub Green

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 5:00 AM UTC (10:30 AM IST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'sagarmajumder2021-afk'
          git config --global user.email 'airelatedworkuse@gmail.com'
          
      - name: Update Daily Log
        run: |
          echo "✅ Daily update - $(date)" >> daily-log.txt
          echo "" >> daily-log.txt
          
      - name: Commit and Push Changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "💚 Auto commit - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}